#!/bin/sh

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.h$`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Starting precommit..."

if [ "$SFILES" != "" ]
then
    echo "Linting code..."
    for FILE in $SFILES
    do
        clang-format --verbose --style=file -i "$PROJECT/$FILE"
        git add "$PROJECT/$FILE"
        FILES="$FILES $FILE"
    done
fi

exit $?